name: build analyze,scan
on:
  push:
    branches:
      - master

jobs:
  build-analyze-scan:
    name: build
    runs: [self-hosted]
    steps:
      - name: checkout the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Building code and analyze with SonarQube
        uses: actions/checkout@master
        env:
          SONAR_TOKEN: ${{ secret.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secret.SONAR_HOST_URL }}  
      - name: dependencies install
        run: npm install
      - name: trivy scan
        run: trivy -fs . > trivy-report.txt
      - name: docker build push
        run:
          docker build -t swiggy .
          docker tag swiggy mohan08129/swiggy:latest
          docker login -u ${{ secret.DOCKER_USERNAME }} -p {{ secret.DOCKER_TOKEN }}
          docker push mohan08129/swiggy:latest
        env:
          DOCKER_CLI_ACL: 1  
  deploy:
    name: deploy app to docker
    needs: build analyze-scan   
    runs-on: [self-hosted]    
    steps:
      - name: docker pull
        run: docker pull mohan08129/swiggy:latest
      - name: image scan
        run: trivy image mohan08129/swiggy:latest > image-trivy-scan.txt
      - name: run docker container
        run: docker run -itd -p 3000:3000 --name swiggy mohan08129/swiggy:latest
